---
name: gottl-dev
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgers

  caddy:
    container_name: caddy
    image: caddy:latest
    entrypoint: caddy run --config /root/Caddyfile
    volumes:
      - $PWD/dev-stack/caddy/Caddyfile.dev:/root/Caddyfile
      - $PWD/public:/srv
      - caddy:/data
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - $PWD/dev-stack/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $PWD/dev-stack/grafana/dashboards:/provisioning/dashboards
      - $PWD/dev-stack/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
      - pyroscope
      - alloy

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - $PWD/dev-stack/tempo/tempo.yaml:/etc/tempo.yaml

  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - $PWD/dev-stack/loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/loki.yaml"

  pyroscope:
    container_name: pyroscope
    image: pyroscope/pyroscope:latest
    ports:
      - "4040:4040"
    command:
      - "server"
    volumes:
      - $PWD/dev-stack/pyroscope/server.yaml:/etc/pyroscope/server.yaml

  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      # grpc
      - "4317:4317"
      # http
      - "4318:4318"
    volumes:
      - $PWD/dev-stack/alloy/config.alloy:/etc/alloy/config.alloy
      - $PWD/logs/gottl.dev.log:/logs/gottl.dev.log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
      - tempo
      - loki
    command: <|
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy"

volumes:
  postgres:
  caddy:
